<?php
/**
 * partial loop of Tutors
 * Tutors
 */
 
    $dataRow       = $this->dataRow;
    
?>
<tr>
    
    <td>
        <?php echo $dataRow->TutorId;?>
    </td>
    
    <td style="vertical-align: middle">
        <?php if($dataRow->Status):?><span class="btn btn-success">Verify</span><?php endif;?>
        <?php if(!$dataRow->Status):?><span class="btn btn-default">Untrust</span><?php endif;?>
    </td>

    <td>
    	<a href="/tutors/update-tutors/id/<?php echo $dataRow->TutorId; ?>" title="update">
        	<?php echo $dataRow->UserName;?>
        </a>
    </td>

    <!-- <td> -->
        <?php //echo $dataRow->Gender;?>
    <!-- </td> -->

    <!-- <td> -->
        <?php //echo $dataRow->Birthday;?>
    <!-- </td> -->

    <td>
        <?php echo $dataRow->Email;?>
    </td>

    <!-- <td> -->
        <?php //echo $dataRow->Address;?>
    <!-- </td> -->

    <td>
        <?php echo $dataRow->Phone;?>
    </td>

    <td>
        <?php $levels = unserialize(TUTOR_LEVELS); echo $levels[$dataRow->Level]?>
    </td>

    <!-- <td> -->
        <?php //echo $dataRow->University;?>
    <!-- </td> -->

    <td style="max-width: 150px;">
        <?php echo $dataRow->Subject;?>
    </td>

    <!-- <td> -->
        <?php //echo $dataRow->Graduation;?>
    <!-- </td> -->

    <td>
        <?php $careers = unserialize(TUTOR_CAREERS); echo $careers[$dataRow->Career]?>
    </td>

    <!-- <td> -->
        <?php //echo $dataRow->Introduction;?>
    <!-- </td> -->

    <td>
        <?php echo $dataRow->CreatedDate;?>
    </td>

    <td style="vertical-align: middle">
        <?php if(!$dataRow->IsDisabled):?><span class="label label-success">Active</span><?php endif;?>
        <?php if($dataRow->IsDisabled):?><span class="label label-default">Inactive</span><?php endif;?>
    </td>

    <!-- <td> -->
        <?php //echo $dataRow->Avatar;?>
    <!-- </td> -->
    
    <td>
        <a href="/tutors/update-tutors/id/<?php echo $dataRow->TutorId; ?>" class="btn btn-warning"> <i class="icon-edit"></i> 
           Update
        </a>
        <!--<a href="/tutors/delete-tutors/id/<?php //echo $dataRow->TutorId; ?>" class="btn btn-danger btn-delete"> <i class="icon-remove icon-white"></i> 
           Delete
        </a>-->
    </td>
</tr>