<?php 
    $form = $this->form;
?>

<div class="row-fluid">
    <div class="span12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller' => $this->text(strtolower('NewsCategories')), 'action'=>$this->showAllUrl), null, true) ?>" >	
                  Back to list <?php echo $this->text('NewsCategories'); ?>
              </a>
          </div>
          <h2>
              Add <?php echo $this->text('NewsCategories'); ?>        
          </h2>
    </div>
</div>

<div class="row-fluid">	
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<div class="row-fluid">
    <div class="span12">
        <form class="form-horizontal" method="post" action="">
            <fieldset>
                
                <?php echo $this->renderFormElement($form->NewsCategoryId);?>
                <?php echo $this->renderFormElement($form->NewsCategoryName);?>
                <?php echo $this->renderFormElement($form->NewsCategoryCode);?>
                <?php echo $this->renderFormElement($form->CreatedDate);?>
                <?php echo $this->renderFormElement($form->IsDisabled);?>
                
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Submit</button>
                    <button type="reset" class="btn"><i class="icon-refresh"></i> Reset</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>