<?php 
    $form = $this->form;
    $controller = ltrim(preg_replace("/([A-Z])/", "-$1", 'Classes'), '-');
    $label = $form->getElement('Save')->getLabel();
    $title = ($label == 'Delete')? 'Delete' : 'Update' ;
    if($label == 'Add') $title = 'Add';
?>

<div class="row-fluid">
    <div class="span12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller' => $this->text(strtolower($controller)), 'action'=>$this->showAllUrl), null, true) ?>" >	
                  Back to list <?php echo $this->text('Classes'); ?>
              </a>
          </div>
          <h2>
              <?php echo $title.' '.$this->text($controller); ?>        
          </h2>
    </div>
</div>

<div class="row-fluid">	
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<div class="row-fluid">
    <div class="span12">
        <form class="form-horizontal" method="post" action="" id="frmClass">
            <fieldset>
                
                <?php echo $this->renderFormElement($form->ClassId);?>
                <?php echo $this->renderFormElement($form->DistrictId);?>
                <?php echo $this->renderFormElement($form->ClassAddress);?>
                <?php echo $this->renderFormElement($form->ClassContact);?>
                <?php echo $this->renderFormElement($form->ClassCost);?>
                <?php echo $this->renderFormElement($form->ClassDaysOfWeek);?>
                <?php echo $this->renderFormElement($form->ClassTime);?>
                <?php echo $this->renderFormElement($form->ClassRequire);?>
                <?php echo $form->ClassTutors;?>
                <?php echo $form->ClassSubjects;?>
                <?php echo $this->renderFormElement($form->ClassGrade);?>
                <?php echo $this->renderFormElement($form->ClassStatus);?>
                <?php if($label !=='Add') echo $this->renderFormElement($form->CreatedDate);?>
                <?php echo $this->renderFormElement($form->IsDisabled);?>
                <?php if($label !=='Add') echo $this->renderFormElement($form->LastUpdated);?>
                <?php //echo $this->renderFormElement($form->LastUpdatedBy);?>
                <?php echo $this->renderFormElement($form->Save);?>
                <?php if($label !=='Delete') echo $this->renderFormElement($form->Reset);?>
                
            </fieldset>
        </form>
    </div>
</div>