<?php 
    $form = $this->form;
    $controller = ltrim(preg_replace("/([A-Z])/", "-$1", 'Classes'), '-');
?>

<div class="row-fluid">
    <div class="span12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller' => $this->text(strtolower($controller)), 'action'=>$this->showAllUrl), null, true) ?>" >
                  Back to list <?php echo $this->text($controller); ?>
              </a>
          </div>
          <h2>
              Delete <?php echo $this->text($controller); ?>        
          </h2>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <form class="form-horizontal" method="post" action="">
            <fieldset>
                			<h2>Are you sure you want to delete this item?</h2>
                			
                			<?php echo $this->renderFormElement($form->ClassId);?>
                <?php echo $this->renderFormElement($form->ClassAddress);?>
                <?php echo $this->renderFormElement($form->ClassContact);?>
                <?php echo $this->renderFormElement($form->ClassCost);?>
                <?php echo $this->renderFormElement($form->ClassDaysOfWeek);?>
                <?php echo $this->renderFormElement($form->ClassTime);?>
                <?php echo $this->renderFormElement($form->ClassRequire);?>
                <?php echo $this->renderFormElement($form->ClassTutors);?>
                <?php echo $this->renderFormElement($form->ClassSubjects);?>
                <?php echo $this->renderFormElement($form->ClassMember);?>
                <?php echo $this->renderFormElement($form->ClassStatus);?>
                <?php echo $this->renderFormElement($form->CreatedDate);?>
                <?php echo $this->renderFormElement($form->IsDisabled);?>
                <?php echo $this->renderFormElement($form->LastUpdated);?>
                <?php echo $this->renderFormElement($form->LastUpdatedBy);?>
                
                <div class="form-actions">
                    <input type="hidden" name="value" id="value" value="<?php $this->id?>">
                    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Submit</button>
                    <button type="button" class="btn"><i class="icon-refresh"></i>
                    	<a href="<?php echo $this->url(array('controller' => $this->text(strtolower($controller)), 'action'=>$this->showAllUrl), null, true) ?>" >
                     		Cancel
                     	</a>
                     </button>
                </div>
            </fieldset>
        </form>
    </div>
</div>