<div class="row-fluid">
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<?php 
    $controller = ltrim(preg_replace("/([A-Z])/", " $1", 'Tutors'), ' ');

$typeSearchs = array(
    'All' => 'All',
    //'TutorId'                      => $this->text('TutorId', false),
    'UserName'                     => $this->text('UserName', false),
    //'Gender'                       => $this->text('Gender', false),
    //'Birthday'                     => $this->text('Birthday', false),
    'Email'                        => $this->text('Email', false),
    //'Address'                      => $this->text('Address', false),
    'Phone'                        => $this->text('Phone', false),
    //'Level'                        => $this->text('Level', false),
    'University'                   => $this->text('University', false),
    'Subject'                      => $this->text('Subject', false),
    //'Graduation'                   => $this->text('Graduation', false),
    //'Career'                       => $this->text('Career', false),
    //'Introduction'                 => $this->text('Introduction', false),
    //'CreatedDate'                  => $this->text('CreatedDate', false),
    //'IsDisabled'                   => $this->text('IsDisabled', false),
    //'Avatar'                       => $this->text('Avatar', false),
    //'Status'                       => $this->text('Status', false),
);
$buttons = array();
echo $this->searchBar($typeSearchs, null, $buttons);

?>
<div class="tutor-title">
	<?php echo $this->text($controller) ?>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php $this->renderTh('Tutor Id'); ?>
                    <?php $this->renderTh('Status'); ?>
                    <?php $this->renderTh('User Name'); ?>
                    <?php $this->renderTh('Email'); ?>
                    <?php $this->renderTh('Phone'); ?>
                    <?php $this->renderTh('Level'); ?>
                    <?php $this->renderTh('Subject'); ?>
                    <?php $this->renderTh('Career'); ?>
                    <?php //$this->renderTh('Avatar'); ?>
                    
                    <th style="vertical-align: middle;">Actions</th>
                </tr>
            </thead>

            <tbody lastest-news-content>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('tutors/_partial/ajax-show-tutors.phtml', array('dataRow'=>$row, 'ctutors' => $this->ctutors) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'tutors/_partial/show-tutors-pagination.phtml'); ?>
    </div>
</div>
<script>
$("input[type=checkbox][class=modal-checkbox]").each(function() {
	$(this).live('click', function() {
		var tutors = '';
    	if($(this).is(':checked')){
    		var data = $.trim($('#ClassTutors').val());
    		if($.trim(data) != '') data += ',';
        	arr =  $.unique((data+$(this).val()).split(','));
        	tutors = arr.join(","); //get unique string back with
        	$('#ClassTutors').val(tutors);        	
    	}else{
    		var data = $.trim($('#ClassTutors').val());
        	y =  data.split(',');
    		y.splice( $.inArray($(this).val(), y), 1 );
    		tutors = y.join(","); //get unique string back with
    		$('#ClassTutors').val(tutors);
        }

    	$('.pagination li a').each(function() {
			var url = $(this).attr('onclick');
			var urlArr = url.split("','");
			var urlPart = urlArr[0];
			var tutorArr = urlArr[0].split('/ctutors/');
			if(tutorArr.length){
				var newUrl = tutorArr[0]+'/ctutors/'+tutors+"','"+urlArr[1];
				$(this).attr('onclick', newUrl);
			}
    	});
	});        
});                    
</script>