<div class="row-fluid">
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<?php 
    $controller = ltrim(preg_replace("/([A-Z])/", " $1", 'Tutors'), ' ');

$typeSearchs = array(
    'All' => 'All',
    'UserName'                     => $this->text('UserName', false),
    'Email'                        => $this->text('Email', false),
    'Phone'                        => $this->text('Phone', false),
    'University'                   => $this->text('University', false),
    'Subject'                      => $this->text('Subject', false),
);
$buttons = array();
$url = $this->url(array('controller'=>'tutors','action'=>'ajax-show-tutors', 'keywords' => '', 'fieldsearch' => ''));
echo $this->searchBar($typeSearchs, 'ajax', $buttons, null, $url);
?>
<div class="tutor-title">
	<?php echo $this->text($controller) ?>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php $this->renderTh('@ajax@Tutor Id'); ?>
                    <?php $this->renderTh('@ajax@Status'); ?>
                    <?php $this->renderTh('@ajax@User Name'); ?>
                    <?php $this->renderTh('@ajax@Email'); ?>
                    <?php $this->renderTh('@ajax@Phone'); ?>
                    <?php $this->renderTh('@ajax@Level'); ?>
                    <?php $this->renderTh('@ajax@Subject'); ?>
                    <?php $this->renderTh('@ajax@Career'); ?>
                    <?php //$this->renderTh('Avatar'); ?>
                    
                    <th style="vertical-align: middle;">Actions</th>
                </tr>
            </thead>

            <tbody lastest-news-content>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('tutors/_partial/ajax-show-tutors.phtml', array('dataRow'=>$row, 'ctutors' => $this->ctutors) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator, $this->url(array('controller'=>'tutors','action'=>'ajax-show-tutors','perpage'=>''))); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'tutors/_partial/show-tutors-pagination.phtml'); ?>
    </div>
</div>
<script>
$("input[type=checkbox][class=modal-checkbox]").each(function() {
	$(this).live('click', function() {
		var tutors = '';
    	if($(this).is(':checked')){
    		var data = $.trim($('#ClassTutors').val());
    		if($.trim(data) != '') data += ',';
        	arr =  $.unique((data+$(this).val()).split(','));
        	tutors = arr.join(","); //get unique string back with
        	$('#ClassTutors').val(tutors);        	
    	}else{
    		var data = $.trim($('#ClassTutors').val());
        	y =  data.split(',');
    		y.splice( $.inArray($(this).val(), y), 1 );
    		tutors = y.join(","); //get unique string back with
    		$('#ClassTutors').val(tutors);
        }

    	$('.pagination li a').each(function() {
			var url = $(this).attr('onclick');
			var urlArr = url.split("','");
			var urlPart = urlArr[0];
			var tutorArr = urlArr[0].split('/ctutors/');
			if(tutorArr.length){
				var newUrl = tutorArr[0]+'/ctutors/'+tutors+"','"+urlArr[1];
				$(this).attr('onclick', newUrl);
			}
    	});
	});        
});                   
$('.btn-search').click(function() {
	var sq = $('.search-query').val();
	var fs = $('#fieldsearch').val();
	var url =  '<?php echo $_SERVER['REQUEST_URI'] ?>';
	curl = url.split('keywords');
	if(curl.length > 1){
		url = replaceParam(url, 'keywords', sq)+'/';
		url = replaceParam(url, 'fieldsearch', fs);
	}else{
		url = "<?php echo $this->url(array('controller'=>'tutors','action'=>'ajax-show-tutors'));?>";
		url += '/keywords/'+sq+'/fieldsearch/'+fs;
	}
	loadPage(url);
}); 
function replaceParam(url, paramName, paramValue){
	var pattern = new RegExp('('+paramName+'/).*?(&|$)') 
        var newUrl = url.replace(pattern,'$1' + paramValue + '$2');
        var n=url.indexOf(paramName);
        if(n == -1){
            newUrl = newUrl + paramName + '/' + paramValue; 
        }
		return newUrl;
}
</script>