<div class="row-fluid">
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<?php 
    $controller = ltrim(preg_replace("/([A-Z])/", " $1", 'Tutors'), ' ');
?>

<div class="row-fluid show-grid">
    <div class="span12">
        <h2>
            <?php echo $this->text($controller) ?>
        </h2>
    </div>
</div>
<?php
$typeSearchs = array(
    'All' => 'All',
    //'TutorId'                      => $this->text('TutorId', false),
    'UserName'                     => $this->text('UserName', false),
    //'Gender'                       => $this->text('Gender', false),
    //'Birthday'                     => $this->text('Birthday', false),
    'Email'                        => $this->text('Email', false),
    //'Address'                      => $this->text('Address', false),
    'Phone'                        => $this->text('Phone', false),
    //'Level'                        => $this->text('Level', false),
    'University'                   => $this->text('University', false),
    'Subject'                      => $this->text('Subject', false),
    //'Graduation'                   => $this->text('Graduation', false),
    //'Career'                       => $this->text('Career', false),
    //'Introduction'                 => $this->text('Introduction', false),
    //'CreatedDate'                  => $this->text('CreatedDate', false),
    //'IsDisabled'                   => $this->text('IsDisabled', false),
    //'Avatar'                       => $this->text('Avatar', false),
    //'Status'                       => $this->text('Status', false),
);
$buttons = array(
    "<a class='btn btn-small btn-primary'  
        href='{$this->url(array('action' => 'add-'. $this->controller))}'>
        <i class='icon-plus'></i>
        Add {$this->text('Tutors')}
    </a>"
);
echo $this->searchBar($typeSearchs, null, $buttons);

?>


<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php $this->renderTh('Tutor Id'); ?>
                    <?php $this->renderTh('Status'); ?>
                    <?php $this->renderTh('User Name'); ?>
                    <?php //$this->renderTh('Gender'); ?>
                    <?php //$this->renderTh('Birthday'); ?>
                    <?php $this->renderTh('Email'); ?>
                    <?php //$this->renderTh('Address'); ?>
                    <?php $this->renderTh('Phone'); ?>
                    <?php $this->renderTh('Level'); ?>
                    <?php //$this->renderTh('University'); ?>
                    <?php $this->renderTh('Subject'); ?>
                    <?php //$this->renderTh('Graduation'); ?>
                    <?php $this->renderTh('Career'); ?>
                    <?php //$this->renderTh('Introduction'); ?>
                    <?php $this->renderTh('Created Date'); ?>
                    <?php $this->renderTh('Is Disabled'); ?>
                    <?php //$this->renderTh('Avatar'); ?>
                    
                    <th style="vertical-align: middle;">Actions</th>
                </tr>
            </thead>

            <tbody>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('tutors/_partial/show-tutors.phtml', array('dataRow'=>$row) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </div>
</div>
