<?php 
    $form = $this->form;    
    $controller = ltrim(preg_replace("/([A-Z])/", "-$1", 'News'), '-');
    $label = $form->getElement('Save')->getLabel();
    $title = ($label == 'Delete')? 'Delete' : 'Update' ;
    if($label == 'Add') $title = 'Add';
?>

<div class="row-fluid">
    <div class="span12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller' => $this->text(strtolower($controller)), 'action'=>$this->showAllUrl), null, true) ?>" >	
                  Back to list <?php echo $this->text('News'); ?>
              </a>
          </div>
          <h2>
              <?php echo $title.' '.$this->text($controller); ?>        
          </h2>
    </div>
</div>

<div class="row-fluid">	
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<?php
						$imageUrl = trim($form->ImageUrl->getValue());
                        if(!empty($imageUrl)){
                            $filename = IMAGE_UPLOAD_PATH.$imageUrl;
                            $imageStyle = 'width="200" height="200"';
                            if(file_exists($filename)){
                                $imageInfo = getimagesize($filename);
                                $imageSize = number_format(filesize($filename)/1024, 1.,'.', ',').' kB';
                                $imageDimension = $imageInfo[0].' x '.$imageInfo[1].' px';
//                                if($imageInfo[0] < 200 && $imageInfo[1] < 200)
//                                    $imageStyle = 'width="'.$imageInfo[0].'" height="'.$imageInfo[1].'"';
                            }
                        }else $imageUrl = 'none.gif';
                    ?>

<div class="row-fluid">
    <div class="span12">
        <form class="" method="post" action="" id="frmImage">
        <div class="form-horizontal">
	        <div class="row-fluid">
	            <div class="span8">
		            <fieldset class="form-vertical">
		                <?php echo $this->renderFormElement($form->NewsId, 1);?>
		                <?php echo $this->renderFormElement($form->Title, 1);?>
		                <?php echo $this->renderFormElement($form->Summary, 1);?>
		                <?php if($label !=='Delete' ) echo $this->renderFormElement($form->Content, 1);?>
		                <?php echo $this->renderFormElement($form->Save);?>
		                <?php if($label !=='Delete') echo $this->renderFormElement($form->Reset);?>
		                </fieldset>
	              </div>
		           <div class="span4">
			            <fieldset class="form-vertical">
			                <?php echo $this->renderFormElement($form->NewsCategoryId, 1);?>
			                <?php echo $this->renderFormElement($form->IsDisabled);?>
			                <?php echo $this->renderFormElement($form->IsPrivate);?>
			                <?php if($label !=='Add') echo $this->renderFormElement($form->CreatedDate, 1);?>
			         <?php if($label !=='Delete' ):?>       
			                <div class="control-group">
			                	<label for="ImageUrl" class="control-label">Image Upload</label>
	                            <label class="control-label view-label" for="inputEmail"> </label>
	                            <div class="controls" style="position: relative;">
	                              <div id="file-uploader"></div><img id="progress-img" src="/scripts/upload/loading.gif"/>
	                            </div>
	                          </div>
	                        <div class="control-group">
	                            <div class="controls">
	                                Drop image here to upload<br>
	                                Recommend image demension: 200 x 200 (px)<br>
	                                Accepted extensions: jpg, png, gif. Maximum size: <?php echo IMAGE_SIZE_LIMIT; ?> kB
	                            </div>
	                        </div>
	                        <div class="control-group">
	                            <label class="control-label view-label" for="inputSection"><strong>Image Name</strong></label>
	                            <div class="controls">
	                              <div class="help-inline" id="image-name" old-image-name="<?php echo $imageUrl;?>">
	                                  <?php echo $imageUrl;?>
	                              </div>
	                            </div>
	                        </div>
	                        <div class="control-group">
		                            <label class="control-label view-label" for="inputSection"><strong>Thumb</strong></label>
		                            <div class="controls">
		                                <div id="image-thumb">
		                                    <a class="image-in-modal" url="<?php echo IMAGE_UPLOAD_URL?>" tmpUrl="<?php echo IMAGE_UPLOAD_URL_TMP?>" filename="<?php echo $imageUrl?>" href="#">
		                                        <img alt="<?php echo $imageUrl?>" title="+" src="<?php echo IMAGE_UPLOAD_URL.$imageUrl?>" <?php echo !empty($imageStyle)?$imageStyle:''?>/>
		                                    </a>
		                                </div>
		                            </div>
		                        </div>		                        
		                        <div class="control-group">
		                            <div class="controls">
		                              <ul id="separate-list" style="display:none"></ul>
		                            </div>
		                          </div>
			                <?php //echo $this->renderFormElement($form->ImageUrl, 1);?>
			                <?php endif;?>	
			            </fieldset>
		            </div>
		         </div>
	         </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
    	tinymce.init({
    	    selector: "textarea",
    	    theme: "modern",
    	    plugins: [
    	        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
    	        "searchreplace wordcount visualblocks visualchars code fullscreen",
    	        "insertdatetime media nonbreaking save table contextmenu directionality",
    	        "emoticons template paste textcolor colorpicker textpattern"
    	    ],
    	    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    	    toolbar2: "print preview media | forecolor backcolor emoticons",
    	    image_advtab: true,
    	    templates: [
    	        {title: 'Test template 1', content: 'Test 1'},
    	        {title: 'Test template 2', content: 'Test 2'}
    	    ],

    	    doctype : "<!DOCTYPE html>",

    	    convert_urls : false,

    	    //template_external_list_url : "gen4tinymce/lists/template_list.js",
    	    external_link_list_url : "gen4tinymce/lists/link_list.js",
    	    //media_external_list_url : "gen4tinymce/lists/media_list.js",
    	        
    	    valid_elements : "@[id|class|style|title|dir<ltr?rtl|lang|xml::lang],"
    	    + "a[rel|rev|charset|hreflang|tabindex|accesskey|type|"
    	    + "name|href|target|title|class],strong/b,em/i,strike,u,span[class|align|style],"
    	    + "p[style],,-ol[type|compact],-ul[type|compact],-li,br,img[longdesc|usemap|"
    	    + "src|border|alt=|title|hspace|vspace|width|height|align],-sub,-sup,"
    	    + "-blockquote,-table[border=0|cellspacing|cellpadding|width|frame|rules|"
    	    + "height|align|summary|bgcolor|background|bordercolor],-tr[rowspan|width|"
    	    + "height|align|valign|bgcolor|background|bordercolor],tbody,thead,tfoot,"
    	    + "#td[colspan|rowspan|width|height|align|valign|bgcolor|background|bordercolor"
    	    + "|scope],#th[colspan|rowspan|width|height|align|valign|scope],caption,-div,"
    	    + "-span,-code,-pre,address,-h1,-h2,-h3,-h4,-h5,-h6,hr[size|noshade],-font[face"
    	    + "|size|color],dd,dl,dt,cite,abbr,acronym,del[datetime|cite],ins[datetime|cite],"
    	    + "object[classid|width|height|codebase|*],param[name|value|_value],embed[type|width"
    	    + "|height|src|*],map[name],area[shape|coords|href|alt|target],bdo,"
    	    + "button,col[align|char|charoff|span|valign|width],colgroup[align|char|charoff|span|"
    	    + "valign|width],dfn,fieldset,form[action|accept|accept-charset|enctype|method],"
    	    + "input[accept|alt|checked|disabled|maxlength|name|readonly|size|src|type|value],"
    	    + "kbd,label[for],legend,noscript,optgroup[label|disabled],option[disabled|label|selected|value],"
    	    + "q[cite],samp,select[disabled|multiple|name|size],small,"
    	    + "textarea[cols|rows|disabled|name|readonly],tt,var,big",

    	    extended_valid_elements : "p[style],span[style]",
    	    valid_children : "+body[style], span[style]",
    	    inline_styles : true,
    	    verify_html : false
    	});                   
    });
</script>