<?php 
    $form = $this->form;
?>

<div class="row-fluid show-grid form-horizontal">
    <div class="span12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller' => $this->text(strtolower('News')), 'action'=>$this->showAllUrl), null, true) ?>" >	
                  Back to list <?php echo $this->text('News'); ?>
              </a>
          </div>
          <h2>
              Update <?php echo $this->text('News'); ?>        
          </h2>
    </div>
</div>

<div class="row-fluid">
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<div class="row-fluid show-grid form-horizontal">
    <div class="span12">
        <form class="form-horizontal" method="post" action="">
            <fieldset>
                
                <?php echo $this->renderFormElement($form->NewsId);?>
                <?php echo $this->renderFormElement($form->Title);?>
                <?php echo $this->renderFormElement($form->Summary);?>
                <?php echo $this->renderFormElement($form->UserId);?>
                <?php echo $this->renderFormElement($form->Content);?>
                <?php echo $this->renderFormElement($form->ImageUrl);?>
                <?php echo $this->renderFormElement($form->CreatedDate);?>
                <?php echo $this->renderFormElement($form->IsPrivate);?>
                <?php echo $this->renderFormElement($form->NewsCategoryId);?>
                
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Submit</button>
                    <button type="reset" class="btn"><i class="icon-refresh"></i> Reset</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){

    	tinymce.init({
    	    selector: "textarea",
    	    theme: "modern",
    	    plugins: [
    	        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
    	        "searchreplace wordcount visualblocks visualchars code fullscreen",
    	        "insertdatetime media nonbreaking save table contextmenu directionality",
    	        "emoticons template paste textcolor colorpicker textpattern"
    	    ],
    	    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    	    toolbar2: "print preview media | forecolor backcolor emoticons",
    	    image_advtab: true,
    	    templates: [
    	        {title: 'Test template 1', content: 'Test 1'},
    	        {title: 'Test template 2', content: 'Test 2'}
    	    ]
    	});           
        
        /*tinyMCE.init({
            // General options
            //mode : "textareas",
            selector: "textarea",
            theme : "modern",
            width : "600",
            height : "200",
            // Theme options
            theme_advanced_buttons1 : "bold,removeformat",
            removeformat_selector : 'div,table,em,i,span,ins,ul,li',
            theme_advanced_resizing : true,
            forced_root_block : false,
            force_br_newlines : true,	
            force_p_newlines : false,
            plugins: [
                      "advlist autolink lists link image charmap print preview anchor",
                      "searchreplace visualblocks code fullscreen",
                      "insertdatetime media table contextmenu paste moxiemanager"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            onchange_callback: function(editor) {
                tinyMCE.triggerSave();
                $("#" + editor.id).valid();
            }
        });
        
        $(".form-horizontal").submit(
        function(){
            tinyMCE.triggerSave();
        }
    ).validate({
            ignore: "",
            errorElement: "span",
            errorClass: "help-inline",
            errorPlacement: function(error, element) {
                error.appendTo( element.parent() );                
            },
            highlight: function(element) {                
                $(element).parent().parent().addClass('error');
            },
            unhighlight: function(element) {                
                $(element).parent().parent().removeClass('error');
                
            },
            rules: {
                technology: {
                    required: true
                }
            },
            messages:{
                technology:"Please enter Technology"
            }
        }); */
    });
</script>