<?php 
    $form = $this->form;
    $label = $form->getElement('Save')->getLabel();
    $title = ($label == 'Delete')? 'Delete' : 'Update' ;
    if($label == 'Add') $title = 'Add';
?>

<div class="row-fluid">
    <div class="span12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller' => $this->text(strtolower('Users')), 'action'=>$this->showAllUrl), null, true) ?>" >	
                  Back to list <?php echo $this->text('Users'); ?>
              </a>
          </div>
          <h2>
              <?php echo $title.' '.$this->text('Users'); ?>        
          </h2>
    </div>
</div>

<div class="row-fluid">	
<?php if(!empty($this->message) && isset($this->message[0])):?>
<?php $message = explode("/", $this->message[0]);?>
<div class="span12">
     <div class="alert alert-<?php echo $message[0];?>">
        <button class="close" data-dismiss="alert" type="button">X</button>
        <?php echo $message[1];?>
        <?php if(isset($message[2]))echo "<ul><li>".$message[2]."</li></ul>"?>
    </div>
</div>
<?php endif;?>
</div>

<div class="row-fluid">
    <div class="span12">
        <form class="form-horizontal" method="post" action="">
            <fieldset>
                
                <?php echo $this->renderFormElement($form->UserId);?>
                <?php echo $this->renderFormElement($form->Email);?>
                <?php echo $this->renderFormElement($form->Password);?>
                <?php echo $this->renderFormElement($form->LastName);?>
                <?php echo $this->renderFormElement($form->FirstName);?>
                <?php echo $this->renderFormElement($form->UserName);?>
                <?php echo $this->renderFormElement($form->IsDisabled);?>
                <?php if($label !=='Add') echo $this->renderFormElement($form->LastLogin);?>                
                <?php echo $this->renderFormElement($form->Save);?>
				<?php if($label !=='Delete') echo $this->renderFormElement($form->Reset);?>
            </fieldset>
        </form>
    </div>
</div>