<?php
/**
 * partial loop of News
 * News
 */
 
    $dataRow       = $this->dataRow;
    
?>
<tr>
    
    <td>
        <?php echo $dataRow->NewsId;?>
    </td>

    <td>
       <a href="/news/update-news/id/<?php echo $dataRow->NewsId; ?>" class="">
        	<?php echo $dataRow->Title;?><br/>
         </a>
        <span><small>Category: <?php echo $dataRow->NewsCategoryName;?></small></span>
    </td>

    <td>
        <?php echo $dataRow->CreatedDate;?>
    </td>

    <td style="vertical-align: middle">
        <?php if(!$dataRow->IsDisabled):?><span class="label label-success">Active</span><?php endif;?>
        <?php if($dataRow->IsDisabled):?><span class="label label-default">Inactive</span><?php endif;?>
    </td>
    
    <td>
        <a href="/news/update-news/id/<?php echo $dataRow->NewsId; ?>" class="btn btn-warning"> <i class="icon-edit"></i> 
           Update
        </a>
        <a href="/news/delete-news/id/<?php echo $dataRow->NewsId; ?>" class="btn btn-danger btn-delete"> <i class="icon-remove icon-white"></i> 
           Delete
        </a>
    </td>
</tr>