<?php
echo $this->doctype();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
getHeaders($this, $controller, $action);
?>
<html>
<head>
<?php if ($controller == 'news' && ($action == 'add-news' || $action == 'update-news'))://import google map api ?>
		<!-- <script type="text/javascript" src="/scripts/tinymce/js/tinymce/tinymce.min.js"></script> -->
<?php endif;
        getStyleContents($this, $controller, $action);
        getScriptContents($this, $controller, $action);    
?>
<link href="/images/logo_256px.ico" rel="SHORTCUT ICON">
</head>
<body>

<div class="row">
  <div class="col-md-12">
  <?php echo $this->render("header.phtml"); ?>
  
  </div>
  
</div>
  <?php  echo $this->layout()->content ?>
<div class="row">
  <div class="col-md-12">
  <?php  echo $this->render("footer.phtml"); ?>
  </div>
</div>


</body>
</html>
