<?php
/**
 * partial loop of Configs
 * Configs
 */
 
    $dataRow       = $this->dataRow;
    $multiName = '';
    $multiValue = '';
    $multi = explode('@Multi@', $dataRow->ConfigName);
    if(count($multi) >1){
    	$multiName = $multi[0];
    	$multiValue = unserialize($multi[1]);
    }
?>
<tr>
    
    <td>
        <?php echo $dataRow->ConfigId;?>
    </td>

    <td>
       <a href="/configs/update-configs/id/<?php echo $dataRow->ConfigId; ?>" class="">
        	<?php echo (!empty($multiName))?$multiName:$dataRow->ConfigName;?><br/>
         </a>
        <span><small>Category: <?php echo $dataRow->ConfigCategoryName;?></small></span>
    </td>

    <td>
        <?php echo $dataRow->ConfigCode;?>
    </td>

    <td>
        <?php if(empty($multiName)) 
        			echo $dataRow->ConfigValue;
        		else
					echo $multiValue[$dataRow->ConfigValue];
        ?>
    </td>

    <td style="vertical-align: middle">
        <?php //echo $dataRow->IsDisabled;?>
        <?php if(!$dataRow->IsDisabled):?><span class="label label-success">Active</span><?php endif;?>
        <?php if($dataRow->IsDisabled):?><span class="label label-default">Inactive</span><?php endif;?>
    </td>

    <td>
        <?php echo $dataRow->LastUpdated;?>
    </td>

    <!-- <td> -->
        <?php //echo $dataRow->LastUpdatedBy;?>
    <!-- </td> -->
    
    <td>
        <a href="/configs/update-configs/id/<?php echo $dataRow->ConfigId; ?>" class="btn btn-warning"> <i class="icon-edit"></i> 
           Update
        </a>
       <!-- <a href="/configs/delete-configs/id/<?php //echo $dataRow->ConfigId; ?>" class="btn btn-danger btn-delete"> <i class="icon-remove icon-white"></i> 
           Delete
        </a>-->
    </td>
</tr>