<?php
/**
 * partial loop of NewsCategories
 * NewsCategories
 */
 
    $dataRow       = $this->dataRow;
    
?>
<tr>
    
    <td>
        <?php echo $dataRow->NewsCategoryId;?>
    </td>

    <td>
    	<a href="/news-categories/update-news-categories/id/<?php echo $dataRow->NewsCategoryId; ?>" class="">
        	<?php echo $dataRow->NewsCategoryName;?>
        </a>
    </td>

    <td>
        <?php echo $dataRow->NewsCategoryCode;?>
    </td>

    <td>
        <?php echo $dataRow->CreatedDate;?>
    </td>

    <td style="vertical-align: middle">
        <?php //echo $dataRow->IsDisabled;?>
        <?php if(!$dataRow->IsDisabled):?><span class="label label-success">Active</span><?php endif;?>
        <?php if($dataRow->IsDisabled):?><span class="label label-default">Inactive</span><?php endif;?>
    </td>
    
    <td>
        <a href="/news-categories/update-news-categories/id/<?php echo $dataRow->NewsCategoryId; ?>" class="btn btn-warning"> <i class="icon-edit"></i> 
           Update
        </a>
        <!-- <a href="/news-categories/delete-news-categories/id/<?php //echo $dataRow->NewsCategoryId; ?>" class="btn btn-danger btn-delete"> <i class="icon-remove icon-white"></i> 
           Delete
        </a> -->
    </td>
</tr>