<?php 
    $form = $this->form;
    $controller = ltrim(preg_replace("/([A-Z])/", "-$1", 'ConfigCategories'), '-');
?>

<div class="row-fluid">
    <div class="span12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller' => $this->text(strtolower($controller)), 'action'=>$this->showAllUrl), null, true) ?>" >
                  Back to list <?php echo $this->text('ConfigCategories'); ?>
              </a>
          </div>
          <h2>
              Delete <?php echo $this->text('ConfigCategories'); ?>        
          </h2>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <form class="form-horizontal" method="post" action="">
            <fieldset>
                			<!-- <h2>Are you sure you want to delete this item?</h2> -->
                			
                			<?php echo $this->renderFormElement($form->ConfigCategoryId);?>
			                <?php echo $this->renderFormElement($form->ConfigCategoryName);?>
			                <?php echo $this->renderFormElement($form->ConfigCategoryCode);?>
			                <?php echo $this->renderFormElement($form->CreatedDate);?>
			                <?php echo $this->renderFormElement($form->IsDisabled);?>
                
                <div class="form-actions">
                    <input type="hidden" name="value" id="value" value="<?php $this->id?>">
                    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Delete</button>
                    <button type="button" class="btn"><i class="icon-refresh"></i>
                    	<a href="<?php echo $this->url(array('controller' => $this->text(strtolower($controller)), 'action'=>$this->showAllUrl), null, true) ?>" >
                     		Cancel
                     	</a>
                     </button>
                </div>
            </fieldset>
        </form>
    </div>
</div>