<?php
/**
 * partial loop of Users
 * Users
 */
 
    $dataRow       = $this->dataRow;
    
?>
<tr>
    
    <td>
        <?php echo $dataRow->UserId;?>
    </td>

    <td>
        <a href="mailto:<?php echo $dataRow->Email;?>" title="Send email"><?php echo $dataRow->Email;?></a>
    </td>

    <td>
        <?php echo $dataRow->LastName;?>
    </td>

    <td>
        <?php echo $dataRow->FirstName;?>
    </td>

    <td>
    	<a href="/users/update-users/id/<?php echo $dataRow->UserId; ?>" title="Update">
        	<?php echo $dataRow->UserName;?>
        </a>
    </td>
    
    <td>
        <?php echo $dataRow->OpenId;?>
    </td>
    
    <td>
        <?php $contacts = $dataRow->Contacts; 
        	if($contacts):?>
        	<a href="/contacts/show-contacts/keywords/<?php echo $dataRow->UserId; ?>/fieldsearch/UserId" title="View Contacts">
        		<?php echo $contacts; ?>
        	</a>
        <?php else:?>
        	<?php echo $contacts; ?>
        <?php endif;?>
    </td>

    <td style="vertical-align: middle">
        <?php if(!$dataRow->IsDisabled):?><span class="label label-success">Active</span><?php endif;?>
        <?php if($dataRow->IsDisabled):?><span class="label label-default">Inactive</span><?php endif;?>
    </td>

    <td>
        <?php echo $dataRow->LastLogin;?>
    </td>
    
    <td>
        <a href="/users/update-users/id/<?php echo $dataRow->UserId; ?>" class="btn btn-warning"> <i class="icon-edit"></i> 
           Update
        </a>
        <a href="/users/delete-users/id/<?php echo $dataRow->UserId; ?>" class="btn btn-danger btn-delete"> <i class="icon-remove icon-white"></i> 
           Delete
        </a>
    </td>
</tr>